apiVersion: v1
kind: Service
metadata:
  name: spring-boot-json-logs
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.application.port }}
      targetPort: {{ .Values.application.port }}
      protocol: TCP
      name: http
  selector:
    app: spring-boot-json-logs
    release: {{ .Release.Name }}
